services:
  mongo:
    image: mongo:4.4
    container_name: st_mongodb
    ports:
      - 27017:27017

  file-storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-storage-service
    mem_limit: 1gb
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/storage_db
